# Generated by Django 5.1.4 on 2024-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medic_info',
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, related_name='patient_prescriptions', to='prescriptions.prescription'),
        ),
    ]
