# Generated by Django 5.1.4 on 2024-12-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_medic_info_patient_prescriptions'),
        ('prescriptions', '0002_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_list', to='prescriptions.prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to='patients.patient'),
        ),
    ]
