# Generated by Django 5.1.3 on 2025-06-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='analyze',
            field=models.TextField(blank=True, null=True),
        ),
    ]
