# Generated by Django 5.1.3 on 2025-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convencional', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('injetavel', 'Injetável')], max_length=20)),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
